cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/models/users.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from {{cookiecutter.project_slug_no_hyphen}}.config import db, login


class User(UserMixin, db.Model):
    """
    Just a simple user model with an id as primary key, username, email and the password hash
    """
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/app.py
{% if cookiecutter.setup_type == 'advanced' -%}
import os

import click
from flask import Flask, request, session

from .config import Config, babel, bootstrap, config_mail, db, login, mail, migrate

{% endif %}
{% if cookiecutter.setup_type == 'basic' -%}
from flask import Flask

from .config import Config

{% endif %}

app = Flask(__name__)
app.config.from_object(Config)
{% if cookiecutter.setup_type == 'advanced' -%}
migrate.init_app(app, db)
login.init_app(app)
mail.init_app(app)
bootstrap.init_app(app)
babel.init_app(app)

db.init_app(app)

with app.app_context():
    db.drop_all()
    db.create_all()

config_mail(app){% endif %}

from {{cookiecutter.project_slug_no_hyphen}}.errors import bp as errors_bp  # noqa: E402

app.register_blueprint(errors_bp)

{% if cookiecutter.setup_type == 'basic' -%}
from {{cookiecutter.project_slug_no_hyphen}}.basic import bp as basic_bp  # noqa: E402

app.register_blueprint(basic_bp)
{% endif %}

{% if cookiecutter.setup_type == 'advanced' -%}
from {{cookiecutter.project_slug_no_hyphen}}.auth import bp as auth_bp  # noqa: E402

app.register_blueprint(auth_bp, url_prefix='/auth')

from {{cookiecutter.project_slug_no_hyphen}}.main import bp as main_bp  # noqa: E402

app.register_blueprint(main_bp)


@app.cli.group()
def translate():
    """Translation commands"""
    pass


@translate.command()
@click.argument('lang')
def init(lang):
    """Initialize a new language"""
    if os.system('pybabel extract -F babel.cfg -o messages.pot .'):
        raise RuntimeError('extract command failed')
    if os.system('pybabel init -i messages.pot -d {{ cookiecutter.project_slug_no_hyphen }}/translations -l ' + lang):
        raise RuntimeError('init command failed')
    os.remove('messages.pot')


@translate.command()
def update():
    """Update all languages"""

    if os.system('pybabel extract -F babel.cfg -o messages.pot .'):
        raise RuntimeError('extract command failed')
    if os.system('pybabel update -i messages.pot -d {{ cookiecutter.project_slug_no_hyphen }}/translations'):
        raise RuntimeError('update command failed')
    os.remove('messages.pot')


@translate.command()
def compile():
    """Compile all languages"""

    if os.system('pybabel compile -d {{ cookiecutter.project_slug_no_hyphen }}/translations'):
        raise RuntimeError('compile command failed')


"""This selector checks, if the user selected a language manually and in that case uses this language for translations.
    However, if the user has not selected any language (when accessing the page for the first time, new browser session,
    ...) it will choose the best matching language out of the configured ones, using browser settings and request headers
    "Accept-Language:" property
"""


@babel.localeselector
def get_locale():
    # if the user has set up the language manually it will be stored in the session,
    # so we use the locale from the user settings
    try:
        language = session['language']
    except KeyError:
        language = None
    if language is not None:
        return language
    return request.accept_languages.best_match(Config.LANGUAGES.keys())


"""This function allows us to use all possible language options and the current language in our templates"""


@app.context_processor
def inject_conf_var():
    return dict(
        AVAILABLE_LANGUAGES=Config.LANGUAGES,
        CURRENT_LANGUAGE=session.get('language', request.accept_languages.best_match(Config.LANGUAGES.keys()))){% endif %}

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/basic/__init__.py
from flask import Blueprint

bp = Blueprint('basic', __name__)

from {{cookiecutter.project_slug_no_hyphen}}.basic import routes  # noqa: E402, F401

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/basic/routes.py
from flask import redirect, render_template, url_for
from {{cookiecutter.project_slug_no_hyphen}}.basic import bp


@bp.route('/')
def root():
    return redirect(url_for('basic.index'))

{%- if cookiecutter.frontend == 'none' %}
@bp.route('/index')
def index():
    return render_template('basic_index.html'){%- endif %}


{%- if cookiecutter.frontend == '' %}
@bp.route('/index')
def index():
    return render_template('basic_index.html'){%- endif %}

{%- if cookiecutter.frontend.lower() == 'solidstate' %}
@bp.route('/index')
def index():
    return render_template('basic_index_f.html'){%- endif %}

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from {{cookiecutter.project_slug}}.main import routes  # noqa: E402, F401

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/main/routes.py
from flask import redirect, render_template, session, url_for
from {{cookiecutter.project_slug_no_hyphen}}.main import bp


@bp.route('/language/<language>')
def set_language(language=None):
    session['language'] = language
    return redirect(url_for('main.index'))


@bp.route('/')
def root():
    return redirect(url_for('main.index'))


@bp.route('/index')
def index():
    return render_template('index.html')

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/services/__init__.py
from flask import Blueprint

bp = Blueprint("auth", __name__)

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - MyProject{% else %}{{ _('Welcome to MyProject') }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">MyProject</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="index.html">{{ _('Home') }}</a></li>
                    <li><a href="index.html">{{ _('Explore') }}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>
                    {% else %}
                    <li><a href="{{ url_for('auth.login', username=current_user.username) }}">{{ _('Profile') }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        <div id="language">
                    {% if CURRENT_LANGUAGE == 'en' %}
                    <a href="{{ url_for('auth.set_language', language='de') }}">
                        <p>Click here for german version</p>
                    </a>
                    {% else %}
                    <a href="{{ url_for('auth.set_language', language='en') }}">
                        <p>Klicke hier für die englische Version</p></a>
                    {% endif %}
                </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/templates/basic_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    THIS IS A BASIC WEBSITE SETUP
</body>
</html>

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/templates/basic_index_f.html
<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Solid State by HTML5 UP</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="../static/assets/css/main.css"/>
    <noscript>
        <link rel="stylesheet" href="../static/assets/css/noscript.css"/>
    </noscript>
</head>
<body class="is-preload">

<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Header -->
    <header id="header" class="alt">
        <h1><a href="index.html">Solid State</a></h1>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

    <!-- Menu -->
    <nav id="menu">
        <div class="inner">
            <h2>Menu</h2>
            <ul class="links">
                <li><a href="#">Home</a></li>
            </ul>
            <a href="#" class="close">Close</a>
        </div>
    </nav>

    <!-- Banner -->
    <section id="banner">
        <div class="inner">
            <div class="logo"><span class="icon fa-gem"></span></div>
            </div>
            <h2>This is Solid State</h2>
            <p>Another free + fully responsive site template by <a href="http://html5up.net">HTML5 UP</a></p>
        </div>
    </section>

    <!-- Wrapper -->
    <section id="wrapper">

        <!-- One -->
        <section id="one" class="wrapper spotlight style1">
            <div class="inner">
                <a href="#" class="image"><img src="../static/assets/images/pic01.jpg" alt=""/></a>
                <div class="content">
                    <h2 class="major">Lorem ipsum</h2>
                    <p>Dolor ipsum sit amet.</p>
                    <a href="#" class="special">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Two -->
        <section id="two" class="wrapper alt spotlight style2">
            <div class="inner">
                <a href="#" class="image"><img src="../static/assets/images/pic02.jpg" alt=""/></a>
                <div class="content">
                    <h2 class="major">Tempus adipiscing</h2>
                    <p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris
                        id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
                    <a href="#" class="special">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Three -->
        <section id="three" class="wrapper spotlight style3">
            <div class="inner">
                <a href="#" class="image"><img src="../static/assets/images/pic03.jpg" alt=""/></a>
                <div class="content">
                    <h2 class="major">Nullam dignissim</h2>
                    <p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris
                        id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
                    <a href="#" class="special">Learn more</a>
                </div>
            </div>
        </section>

        <!-- Four -->
        <section id="four" class="wrapper alt style1">
            <div class="inner">
                <h2 class="major">Vitae phasellus</h2>
                <p>Cras mattis ante fermentum, malesuada neque vitae, eleifend erat. Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas,
                    purus ipsum consequat orci, sit amet lobortis lorem lacus in tellus. Sed ac elementum arcu. Quisque placerat auctor laoreet.</p>
                <section class="features">
                    <article>
                        <a href="#" class="image"><img src="../static/assets/images/pic04.jpg" alt=""/></a>
                        <h3 class="major">Sed feugiat lorem</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
                        <a href="#" class="special">Learn more</a>
                    </article>
                    <article>
                        <a href="#" class="image"><img src="../static/assets/images/pic05.jpg" alt=""/></a>
                        <h3 class="major">Nisl placerat</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
                        <a href="#" class="special">Learn more</a>
                    </article>
                    <article>
                        <a href="#" class="image"><img src="../static/assets/images/pic06.jpg" alt=""/></a>
                        <h3 class="major">Ante fermentum</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
                        <a href="#" class="special">Learn more</a>
                    </article>
                    <article>
                        <a href="#" class="image"><img src="../static/assets/images/pic07.jpg" alt=""/></a>
                        <h3 class="major">Fusce consequat</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing vehicula id nulla dignissim dapibus ultrices.</p>
                        <a href="#" class="special">Learn more</a>
                    </article>
                </section>
                <ul class="actions">
                    <li><a href="#" class="button">Browse All</a></li>
                </ul>
            </div>
        </section>

    </section>

    <!-- Footer -->
    <section id="footer">
        <div class="inner">
            <h2 class="major">Get in touch</h2>
            <p>Cras mattis ante fermentum, malesuada neque vitae, eleifend erat. Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas, purus
                ipsum consequat orci, sit amet lobortis lorem lacus in tellus. Sed ac elementum arcu. Quisque placerat auctor laoreet.</p>
            <form method="post" action="#">
                <div class="fields">
                    <div class="field">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name"/>
                    </div>
                    <div class="field">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email"/>
                    </div>
                    <div class="field">
                        <label for="message">Message</label>
                        <textarea name="message" id="message" rows="4"></textarea>
                    </div>
                </div>
                <ul class="actions">
                    <li><input type="submit" value="Send Message"/></li>
                </ul>
            </form>
            <ul class="contact">
                <li class="icon solid fa-home">
                    Untitled Inc<br/>
                    1234 Somewhere Road Suite #2894<br/>
                    Nashville, TN 00000-0000
                </li>
                <li class="icon solid fa-phone">(000) 000-0000</li>
                <li class="icon solid fa-envelope"><a href="#">information@untitled.tld</a></li>
                <li class="icon brands fa-twitter"><a href="#">twitter.com/untitled-tld</a></li>
                <li class="icon brands fa-facebook-f"><a href="#">facebook.com/untitled-tld</a></li>
                <li class="icon brands fa-instagram"><a href="#">instagram.com/untitled-tld</a></li>
            </ul>
            <ul class="copyright">
                <li>&copy; Untitled Inc. All rights reserved.</li>
                <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>
    </section>

</div>

<!-- Scripts -->
<script src="../static/assets/js/jquery.min.js"></script>
<script src="../static/assets/js/jquery.scrollex.min.js"></script>
<script src="../static/assets/js/browser.min.js"></script>
<script src="../static/assets/js/breakpoints.min.js"></script>
<script src="../static/assets/js/util.js"></script>
<script src="../static/assets/js/main.js"></script>

</body>
</html>

cookietemple/create/templates/web/website_python/flask/{{ cookiecutter.project_slug_no_hyphen }}/{{ cookiecutter.project_slug_no_hyphen }}/templates/index.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
<div id="language">
    {% if CURRENT_LANGUAGE == 'en' %}
    <a href="{{ url_for('main.set_language', language='de') }}">
        <p>Click here for german version</p>
    </a>
    {% else %}
    <a href="{{ url_for('main.set_language', language='en') }}">
        <p>Klicke hier für die englische Version</p></a>
    {% endif %}
</div>
<div>
    <a href="{{ url_for('auth.login') }}">{{ _('Login Here') }}</a>
    <a href="{{ url_for('auth.logout') }}">{{ _('Logout Here') }}</a>
</div>
</body>
</html>